#' Print
#'
#' Print method for `cttab`. Long-format objects are first reshaped via
#' \code{\link{cttab_format}}, then drawn with Unicode box characters.
#' Row indentation is taken from leading whitespace on the row name as
#' produced by \code{\link{cttab_format}}.
#'
#' @param x Table generated by \code{cttab}.
#' @param ... Not used.
#'
#' @export
print.cttab <- function(x, ...) {
  if (!(is.matrix(x) || (is.data.frame(x) && !is.matrix(x) && "label" %in% names(x))) ||
      is.null(attr(x, "row_style"))) {
    x <- cttab_format(x)
  }

  if (nrow(x) == 0L) {
    cat("<empty cttab>\n")
    return(invisible(x))
  }

  rowclass   <- attr(x, "row_style")
  tokens     <- strsplit(rowclass, ";", fixed = TRUE)
  span_idx   <- vapply(tokens, function(t) "span" %in% t, logical(1))
  indent_idx <- vapply(tokens, function(t) "indent" %in% t, logical(1))

  if (!is.matrix(x) && is.data.frame(x) && "label" %in% names(x)) {
    # data.frame path: convert to character matrix for the rendering logic.
    # Visual indent for stat rows is applied here (the label itself no
    # longer carries leading whitespace).
    data_cols <- setdiff(names(x), "label")
    mat <- as.matrix(x[, data_cols, drop = FALSE])
    mode(mat) <- "character"
    align <- c("l", rep("c", length(data_cols)))
    col_names <- data_cols
    labels <- as.character(x$label)
    labels[indent_idx] <- paste0("  ", labels[indent_idx])
    x <- cbind(" " = labels, mat)
    colnames(x) <- c("", col_names)
  } else {
    # Legacy matrix path
    align <- c("l", rep("c", ncol(x)))
    col_names <- colnames(x)
    labels <- as.character(rownames(x))
    labels[indent_idx] <- paste0("  ", labels[indent_idx])
    x <- cbind(" " = labels, x)
    colnames(x) <- c("", col_names)
  }

  # Calculate column widths from non-span rows
  l_h <- nchar(colnames(x), type = "width")
  l <- vapply(
    as.data.frame(x[!span_idx, ]),
    function(z) max(c(nchar(z, type = "width"), 0), na.rm = TRUE), numeric(1)
  )
  l <- apply(rbind(l_h, l), 2, max)

  # If span row larger than all combined, expand width
  l_row <- vapply(
    as.data.frame(x[span_idx, ]),
    function(z) max(c(nchar(z, type = "width"), 0), na.rm = TRUE), numeric(1)
  )
  if (l_row[1] > sum(l)) {
    add_l <- ceiling((l_row[1] - sum(l)) / length(l))
    l <- l + add_l
  }

  # Create heading
  th <- mapply(
    FUN = pad_width,
    x = colnames(x),
    width = l,
    align = rep("c", ncol(x))
  )
  th <- paste(th, collapse = "\u2502")
  th <- sprintf("|%s|", th)

  # Create borders
  th_top <- paste(strrep("\u2500", l), collapse = "\u252c")  # \u2500 joined by \u252c
  th_bot <- paste(strrep("\u2500", l), collapse = "\u2534")  # \u2500 joined by \u2534

  tb_tp <- paste0("\u250c", th_top, "\u2510")  # \u250c\u2500\u2500\u252c\u2500\u2500\u2510 top border
  tb_bt <- paste0("\u2514", th_bot, "\u2518")  # \u2514\u2500\u2500\u2534\u2500\u2500\u2518 bottom border
  tb_sep <- paste0("\u251c", th_bot, "\u2524") # \u251c\u2500\u2500\u2534\u2500\u2500\u2524 section separator

  # Table body
  tb <- rep("", nrow(x))
  for (i in seq_len(nrow(x))) {
    if (span_idx[i]) {
      tb[i] <- pad_width(x[i, 1], sum(l) + ncol(x) - 1, "l")
    } else {
      tb[i] <- paste(pad_width(x[i, ], l, align), collapse = "\u2502")
    }
  }
  tb <- sprintf("|%s|", tb)

  # Group consecutive rows into sections starting at each span (banner /
  # header) row, and place a single divider between sections so a banner
  # and its stat rows sit inside the same box.
  section_id <- cumsum(seq_along(tb) %in% which(span_idx))
  if (length(unique(section_id)) > 1L) {
    breaks <- which(diff(section_id) != 0L)  # last row of each section
    body <- character(0)
    prev <- 0L
    for (b in breaks) {
      body <- c(body, tb[(prev + 1L):b], tb_sep)
      prev <- b
    }
    body <- c(body, tb[(prev + 1L):length(tb)])
  } else {
    body <- tb
  }

  tab <- c(tb_tp, th, tb_sep, body, tb_bt)

  cat(tab, sep = "\n")
}

#' Coerce a cttab to a tidy data frame.
#'
#' Returns a clean long-format \code{data.frame} with one row per
#' (row_split, group, variable, statistic) cell, dropping the rendering
#' meta-columns (\code{Group_ID}, \code{Group_Label}, \code{Stat_ID},
#' \code{Row_Style}, \code{Is_Missing}). Useful for piping \code{cttab}
#' output into other table tools.
#'
#' For an already-formatted matrix \code{cttab}, the standard matrix
#' coercion is used.
#'
#' @param x A \code{cttab} object.
#' @param row.names,optional,... Inherited from \code{\link[base]{as.data.frame}}.
#'
#' @return A \code{data.frame}.
#' @export
as.data.frame.cttab <- function(x, row.names = NULL, optional = FALSE, ...) {
  # Already-formatted outputs (matrix or data.frame with label column)
  if (is.matrix(x) || (!is.null(attr(x, "row_style")) && "label" %in% names(x))) {
    return(NextMethod())
  }

  meta_strip <- c("Group_ID", "Group_Label", "Var_ID", "Stat_ID",
                  "Row_Style", "Is_Missing")
  dt <- as.data.table(unclass(x))
  keep <- setdiff(names(dt), meta_strip)
  out <- as.data.frame(dt[, keep, with = FALSE],
                       row.names = row.names, optional = optional)
  attr(out, "group")           <- attr(x, "group")
  attr(out, "row_split")       <- attr(x, "row_split")
  attr(out, "row_split_label") <- attr(x, "row_split_label")
  attr(out, "nest")            <- attr(x, "nest")
  out
}

# pad a character vector to width
#' @keywords internal
pad_width <- function(x, width, align) {
  side <- c(l = "right", c = "both", r = "left")[align]
  w <- width - nchar(x, "width")
  w1 <- floor(w / 2)
  s1 <- strrep(" ", w * (side == "left") + w1 * (side == "both"))
  s2 <- strrep(" ", w * (side == "right") + (w - w1) * (side == "both"))
  paste0(s1, x, s2)
}
